name: Test
permissions: {}
on:
  pull_request:
    paths-ignore:
    - '**.md'
    - 'screenshots/**'
    - 'windows/**'
  push:
    paths-ignore:
    - '**.md'
    - 'screenshots/**'
    - 'windows/**'
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug
        type: boolean
        required: false
        default: false
      os:
        description: Debug OS
        required: true
        type: choice
        options: [ubuntu-latest, macos-13, all]
jobs:
  transcribe:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
        shell: [shell, shell-bin]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Skip debug
      if: >-
        ${{ github.event_name == 'workflow_dispatch' && inputs.debug && !
            ((inputs.os == 'all' || inputs.os == matrix.os) && matrix.shell == 'shell')
        }}
      run: exit 1
    - uses: actions/checkout@v3
    - uses: azuwis/actions/nix@main
      with:
        key: nix-${{ matrix.shell }}-${{ hashFiles('flake.*', 'nix/**') }}
        debug: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
    - uses: cachix/cachix-action@v12
      with:
        name: azuwis
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        # pushFilter: (-source$|\.whl$)
    - name: Build nix devShell
      run: |
        # build nix devShell, and create profile to prevent gc
        echo "Build nix devShell"
        nix -L develop .#${{ matrix.shell }} --profile ~/.local/state/nix/profiles/shell --command true
    - name: Test transcribe
      run: |
        nix -L develop .#${{ matrix.shell }} --command ./PianoTrans.py --cli test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus
        test -e test/cut_liszt.opus.mid
    - uses: azuwis/actions/nix/post@main
