name: "Test"
on:
  pull_request:
    paths-ignore:
    - '**.md'
    - 'screenshots/**'
    - 'windows/**'
  push:
    paths-ignore:
    - '**.md'
    - 'screenshots/**'
    - 'windows/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable debug'
        type: boolean
        required: false
        default: false
jobs:
  transcribe:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          keep-derivations = true
          keep-outputs = true
    - uses: cachix/cachix-action@v12
      with:
        name: azuwis
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Pre cache
      run: |
        mv /nix/store /nix/store.bak
        mv /nix/var/nix/db/db.sqlite /nix/var/nix/db/db.sqlite.bak
    - uses: actions/cache@v3
      with:
        key: pianotrans3-${{ matrix.os }}-${{ hashFiles('flake.*', 'nix/**') }}
        restore-keys: |
          pianotrans3-${{ matrix.os }}-
        path: |
          /nix/store
          /nix/var/nix/db/db.sqlite
    - name: Post cache
      run: |
        if [ ! -e /nix/store ]
        then
          mv /nix/store.bak /nix/store
          mv /nix/var/nix/db/db.sqlite.bak /nix/var/nix/db/db.sqlite
        fi
    - uses: lhotari/action-upterm@v1
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
    - name: Build nix dev env
      run: |
        # build nix dev env, and create profile to prevent gc
        nix --print-build-logs develop --profile "/nix/var/nix/profiles/per-user/$USER/pianotrans" --command true
        # create gcroots for flake inputs to prevent gc
        for archive in $(nix flake archive --json | grep -E -o '/nix/store/[^"]+')
        do
          ln -fsnv $archive "/nix/var/nix/gcroots/per-user/$USER/$(basename $archive)"
        done
    - name: Test transcribe
      run: |
        nix --print-build-logs develop --profile "/nix/var/nix/profiles/per-user/$USER/pianotrans" --command ./PianoTrans.py --cli test/cut_liszt.opus
        test -e test/cut_liszt.opus.mid
    - name: Nix GC
      run: |
        # delete old stuff not relevant to this build
        nix-collect-garbage -d
